FROM python:3.10
WORKDIR /WAY_OUT_PROJECT/src/for_fun_for_main_account
COPY requirements.txt .
RUN pip install -r requirements.txt
ENV PYTHONPATH=/WAY_OUT_PROJECT
CMD ["python3", "for_fun_editing_text.py"]